%YAML:1.0

# init
min_corner_score:     0.1
cell_sz:              10
pyr_levels:           5
pyr_scale:            0.5
min_features_to_init: 200
lk_win_sz:            30

# camera parameters
width : 720
height: 480
cam_fx: 0.0
cam_fy: 0.0
cam_cx: 0.0
cam_cy: 0.0